import { notFound } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { copy, localeSchema } from "@/lib/i18n";
import { searchProperties } from "@/server/brokerage";
import { PropertyCard } from "@/components/property-card";

export default async function HomePage({ params }: { params: Promise<{ locale: string }> }) {
  const parsed = localeSchema.safeParse((await params).locale);
  if (!parsed.success) notFound();
  const locale = parsed.data;
  const text = copy[locale];
  const ar = locale === "ar";
  const selected = await searchProperties({ transaction: "SALE" });
  return <main id="main-content">
    <section className="hero" aria-labelledby="title">
      <Image src="/images/architecture.jpg" alt={ar ? "عمارة سكنية معاصرة — صورة توضيحية" : "Contemporary residential architecture — editorial photograph"} fill sizes="100vw" priority className="hero-image" />
      <div className="hero-shade" />
      <div className="shell hero-content"><p className="kicker">{ar ? "مدينيوم · المملكة العربية السعودية" : "MADINUM · SAUDI ARABIA"}</p><h1 id="title">{ar ? "مكانٌ للحياة." : "A place to live."}<br /><span>{ar ? "مساحةٌ للفرص." : "Room for possibility."}</span></h1><p>{ar ? "لتسكن. لتقيم. لتستثمر. نرى في كل عقار بداية جديدة." : "To live. To stay. To invest. We see a new beginning in every property."}</p></div>
      <div className="hero-caption">{ar ? "منظور أوسع للعقار" : "A wider perspective on property"}</div>
    </section>
    <form className="home-search shell" action={`/${locale}/properties`}><div className="search-intents"><label><input type="radio" name="transaction" value="SALE" defaultChecked /><span>{text.buy}</span></label><label><input type="radio" name="transaction" value="RENT" /><span>{text.rent}</span></label><Link href={`/${locale}/stays`}>{text.stay}</Link></div><div className="home-search-fields"><label>{text.city}<select name="city"><option value="">{text.allCities}</option><option value="jeddah">{text.jeddah}</option><option value="riyadh">{text.riyadh}</option><option value="makkah">{text.makkah}</option></select></label><label>{ar ? "نوع العقار" : "Property type"}<select name="type"><option value="">{ar ? "جميع العقارات السكنية" : "All residential properties"}</option><option value="APARTMENT">{ar ? "شقة" : "Apartment"}</option><option value="VILLA">{ar ? "فيلا" : "Villa"}</option></select></label><button className="button">{text.search}</button><Link href={`/${locale}/property-management`} className="text-link">{ar ? "تملك عقاراً؟" : "Own a property?"}</Link></div></form>
    <section className="positioning shell"><p className="section-index">{ar ? "رؤية متكاملة" : "ONE CONNECTED VISION"}</p><div><h2>{ar ? "العقار أكثر من عنوان." : "Property is more than an address."}</h2><p>{text.introduction}</p><Link className="text-link" href={`/${locale}/about`}>{ar ? "تعرّف على مدينيوم" : "Meet Madinum"}</Link></div></section>
    <section className="editorial shell" id="brokerage"><div className="editorial-photo"><Image src="/images/architecture.jpg" alt={ar ? "تفاصيل واجهة سكنية معاصرة" : "Details of a contemporary residential facade"} fill sizes="(max-width: 768px) 100vw, 50vw" /></div><div className="editorial-copy"><p className="section-index">01 / {text.brokerage}</p><h2>{ar ? "بيت يناسب حياتك،\nوقرار تطمئن إليه." : "A home for your life.\nA decision made with confidence."}</h2><p>{ar ? "من تحديد احتياجك إلى معاينة الخيارات، نساعدك على اتخاذ الخطوة التالية في شراء أو استئجار عقارك السكني." : "From understanding your needs to viewing the options, we help you take the next step in buying or renting a residential property."}</p><div className="inline-actions"><Link className="button" href={`/${locale}/brokerage?transaction=SALE`}>{ar ? "أرغب في الشراء" : "I want to buy"}</Link><Link className="text-link" href={`/${locale}/brokerage?transaction=RENT`}>{ar ? "أرغب في الاستئجار" : "I want to rent"}</Link></div></div></section>
    {selected.valid && selected.listings.length > 0 && <section className="shell featured-section"><div className="section-heading"><h2>{ar ? "عقارات تستحق نظرة." : "Worth a closer look."}</h2><Link className="text-link" href={`/${locale}/properties`}>{ar ? "استكشف العقارات" : "Explore properties"}</Link></div>{selected.listings.some(listing => listing.property.isDemo) && <p className="demo-notice">{ar ? "عروض تجريبية للتطوير — ليست عقارات متاحة." : "Development demo listings — not available properties."}</p>}<div className="property-grid">{selected.listings.slice(0, 3).map(listing => <PropertyCard key={listing.id} listing={listing} locale={locale} />)}</div></section>}
    <section className="hospitality" id="hospitality"><div className="hospitality-copy"><p className="section-index">02 / {ar ? "مدينيوم للضيافة" : "MADINUM HOSPITALITY"}</p><h2>{ar ? "وصلت.\nأنت في مكانك." : "Arrive.\nFeel at home."}</h2><p>{ar ? "إقامات تديرها مدينيوم، للاسترخاء بعد يوم طويل أو للعمل بإيقاعك الخاص. أخبرنا بوجهتك وتواريخك لنساعدك في اختيار إقامتك." : "Madinum-managed stays for unwinding after a long day or working at your own pace. Tell us your destination and dates to find a stay that fits."}</p><Link className="button button-light" href={`/${locale}/stays`}>{ar ? "استكشف الإقامات" : "Explore stays"}</Link></div><div className="hospitality-photo"><Image src="/images/interior.jpg" alt={ar ? "غرفة معيشة هادئة — صورة توضيحية" : "A calm living space — editorial photograph"} fill sizes="(max-width: 768px) 100vw, 60vw" /></div></section>
    <section className="owner-section shell"><p className="section-index">03 / {ar ? "لأصحاب العقارات" : "FOR PROPERTY OWNERS"}</p><div className="owner-heading"><h2>{ar ? "عقارك يستحق\nإدارة ترى أبعد." : "Your property deserves\na longer view."}</h2><p>{ar ? "من التأجير إلى متابعة التشغيل، نربط تفاصيل الإدارة بهدف واحد: أن تكون على اطلاع، وأن يحظى عقارك بالعناية المناسبة." : "From leasing to day-to-day operations, we connect the details so you stay informed and your property receives the care it needs."}</p></div><div className="service-lines">{(ar ? ["إدارة الإيجارات طويلة الأجل", "تشغيل الإقامات القصيرة", "متابعة الصيانة وتقارير الملاك"] : ["Long-term rental management", "Short-stay operations", "Maintenance coordination & owner reporting"]).map((service, index) => <div key={service}><span>0{index + 1}</span><h3>{service}</h3></div>)}</div><Link className="button" href={`/${locale}/property-management`}>{ar ? "لنتحدث عن عقارك" : "Let’s talk about your property"}</Link></section>
    <section className="brand-statement"><div className="shell"><p className="kicker">{text.brand}</p><h2>{ar ? "للساكن. للضيف. للمالك." : "For residents. For guests. For owners."}</h2><p>{ar ? "علاقة واحدة، وحلول تتكامل." : "One relationship. Connected solutions."}</p></div></section>
    <section className="contact-strip shell"><h2>{ar ? "كل بداية تحتاج حواراً." : "Every beginning starts with a conversation."}</h2><Link className="text-link" href={`/${locale}/contact`}>{text.contact}</Link>
    </section>
  </main>;
}

